"""
RAPTOR Dashboard - Reports Generator
=====================================

Generate comprehensive analysis reports from RAPTOR workflow results.

Author: Ayeh Bolouki
Version: 2.2.0
"""

import streamlit as st
import pandas as pd
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional
import sys

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from raptor.dashboard.components.sidebar import render_sidebar, init_session_state

# Page config
st.set_page_config(
    page_title="RAPTOR - Reports",
    page_icon="📋",
    layout="wide"
)

# Initialize
init_session_state()
render_sidebar()

# Main content
st.title("📋 RAPTOR Report Generator")
st.markdown("### Generate comprehensive analysis reports from your workflow")

# Help section
with st.expander("ℹ️ How to use this module"):
    st.markdown("""
    **Purpose:** Generate professional reports from your RAPTOR analysis results.
    
    ## 📊 **Available Report Types**
    
    ### **1. Quality Control Report**
    - Requires: Module 2 (Quality Assessment) complete
    - Contains: Overall quality score, component scores, outlier detection results
    
    ### **2. DE Analysis Report**
    - Requires: Module 7 (Import DE) complete
    - Contains: Per-method statistics, significant genes summary
    
    ### **3. Ensemble Analysis Report**
    - Requires: Module 9 (Ensemble Analysis) complete
    - Contains: Consensus genes, tier breakdown, method comparison
    
    ### **4. Complete Workflow Report**
    - Requires: Multiple modules complete
    - Contains: Everything from QC to ensemble results
    
    ## 💾 **Export Formats**
    
    - **Markdown (.md):** Best for GitHub, documentation
    - **HTML (.html):** View in browser, share easily
    - **Text (.txt):** Plain text, maximum compatibility
    
    ## 📌 **Tips**
    
    - Reports pull data from completed modules automatically
    - Export reports for documentation and publication
    - HTML format best for sharing with collaborators
    """)

st.markdown("---")

# Check what's available in session state
st.markdown("## 📊 Available Data")

available_modules = []
if st.session_state.get('m2_complete', False):
    available_modules.append("✅ Module 2: Quality Assessment")
else:
    available_modules.append("⬜ Module 2: Quality Assessment")

if st.session_state.get('m7_complete', False):
    available_modules.append("✅ Module 7: DE Import")
else:
    available_modules.append("⬜ Module 7: DE Import")

if st.session_state.get('m8_complete', False):
    available_modules.append("✅ Module 8: Parameter Optimization")
else:
    available_modules.append("⬜ Module 8: Parameter Optimization")

if st.session_state.get('m9_complete', False):
    available_modules.append("✅ Module 9: Ensemble Analysis")
else:
    available_modules.append("⬜ Module 9: Ensemble Analysis")

for module in available_modules:
    st.markdown(f"- {module}")

st.markdown("---")

# Report type selection
st.markdown("## 📄 Select Report Type")

report_type = st.radio(
    "Choose report to generate:",
    [
        "Quality Control Report (Module 2)",
        "DE Analysis Summary (Module 7)",
        "Ensemble Analysis Report (Module 9)",
        "Complete Workflow Report (All Modules)"
    ]
)

st.markdown("---")

# ============================================================================
# REPORT GENERATION FUNCTIONS
# ============================================================================

def generate_qc_report_markdown(qc_data: Dict) -> str:
    """Generate QC report in markdown format."""
    
    report = f"""# 🦖 RAPTOR Quality Control Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**RAPTOR Version:** 2.2.0

---

## 📊 Overall Quality

**Overall Quality Score:** {qc_data.get('overall_score', 'N/A')}/100

"""
    
    if 'component_scores' in qc_data:
        report += "## 📈 Component Scores\n\n"
        for component, score in qc_data['component_scores'].items():
            status = "✅" if score >= 80 else "⚠️" if score >= 60 else "❌"
            report += f"- **{component}:** {score:.1f}/100 {status}\n"
        report += "\n"
    
    if 'outliers_detected' in qc_data:
        report += f"\n## 🔍 Outlier Detection\n\n"
        report += f"**Outliers Detected:** {qc_data['outliers_detected']} samples\n\n"
    
    report += "\n---\n\n*Report generated by RAPTOR v2.2.0*\n"
    
    return report

def generate_de_report_markdown(de_results: Dict) -> str:
    """Generate DE analysis report in markdown format."""
    
    report = f"""# 🦖 RAPTOR Differential Expression Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**RAPTOR Version:** 2.2.0

---

## 📊 Summary

**Number of DE Result Files:** {len(de_results)}

"""
    
    for file_name, de_result in de_results.items():
        report += f"\n### {file_name}\n\n"
        report += f"- **Pipeline:** {de_result.pipeline}\n"
        report += f"- **Total Genes:** {de_result.n_genes:,}\n"
        report += f"- **Significant Genes:** {de_result.n_significant:,}\n"
        report += f"- **Up-regulated:** {de_result.n_up:,}\n"
        report += f"- **Down-regulated:** {de_result.n_down:,}\n"
        
        # Calculate percentage
        pct = (de_result.n_significant / de_result.n_genes * 100) if de_result.n_genes > 0 else 0
        report += f"- **% Significant:** {pct:.1f}%\n"
    
    report += "\n---\n\n*Report generated by RAPTOR v2.2.0*\n"
    
    return report

def generate_ensemble_report_markdown(ensemble_result: Dict) -> str:
    """Generate ensemble analysis report in markdown format."""
    
    report = f"""# 🦖 RAPTOR Ensemble Analysis Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**RAPTOR Version:** 2.2.0

---

## 📊 Summary

**Ensemble Method:** {ensemble_result.get('ensemble_method', 'N/A')}  
**Methods Combined:** {ensemble_result.get('n_methods', 0)}  
**Total Consensus Genes:** {ensemble_result.get('n_consensus', 0):,}

---

## 🎯 Confidence Tiers

### Tier 1 (Highest Confidence, p<0.001)
- **Genes:** {ensemble_result.get('tier1_count', 0):,}
- **Use for:** qPCR validation, drug targets

### Tier 2 (High Confidence, p<0.01)
- **Genes:** {ensemble_result.get('tier2_count', 0):,}
- **Use for:** Pathway analysis, GO enrichment

### Tier 3 (Moderate Confidence, p<0.05)
- **Genes:** {ensemble_result.get('tier3_count', 0):,}
- **Use for:** Exploratory analysis

---

## 📋 Input Methods

Methods used in ensemble:
"""
    
    for method in ensemble_result.get('method_names', []):
        report += f"- {method}\n"
    
    report += "\n---\n\n## 💡 Recommendations\n\n"
    report += "- Use **Tier 1 genes** for validation experiments (qPCR, Western blot)\n"
    report += "- Use **Tier 1 + Tier 2** for pathway enrichment analysis\n"
    report += "- Consider all tiers for exploratory network analysis\n"
    
    report += "\n---\n\n*Report generated by RAPTOR v2.2.0*\n"
    
    return report

def generate_complete_report_markdown(
    qc_data: Optional[Dict],
    de_data: Optional[Dict],
    ensemble_data: Optional[Dict],
    opt_data: Optional[Dict]
) -> str:
    """Generate complete workflow report."""
    
    report = f"""# 🦖 RAPTOR Complete Workflow Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**RAPTOR Version:** 2.2.0

---

## 📋 Analysis Overview

This report summarizes the complete RAPTOR RNA-seq analysis workflow.

"""
    
    # QC Section
    if qc_data:
        report += "\n## 1️⃣ Quality Control\n\n"
        report += f"**Overall Quality Score:** {qc_data.get('overall_score', 'N/A')}/100\n\n"
        if 'outliers_detected' in qc_data:
            report += f"**Outliers Detected:** {qc_data.get('outliers_detected', 0)} samples\n\n"
    
    # DE Section
    if de_data:
        report += "\n## 2️⃣ Differential Expression\n\n"
        report += f"**Number of Methods:** {len(de_data)}\n\n"
        
        for file_name, de_result in de_data.items():
            report += f"### {file_name}\n"
            report += f"- Significant genes: {de_result.n_significant:,}\n"
    
    # Optimization Section
    if opt_data:
        report += "\n## 3️⃣ Parameter Optimization\n\n"
        params = opt_data.get('parameters', {}) if isinstance(opt_data, dict) else {}
        if params:
            report += f"**FDR Threshold:** {params.get('fdr_threshold', 'N/A')}\n"
            report += f"**Log2FC Threshold:** {params.get('lfc_threshold', 'N/A')}\n"
            report += f"**Optimized DEGs:** {opt_data.get('n_total', 'N/A')}\n"
    
    # Ensemble Section
    if ensemble_data:
        report += "\n## 4️⃣ Ensemble Analysis\n\n"
        report += f"**Ensemble Method:** {ensemble_data.get('ensemble_method', 'N/A')}\n"
        report += f"**Consensus Genes:** {ensemble_data.get('n_consensus', 0):,}\n"
        report += f"- Tier 1: {ensemble_data.get('tier1_count', 0):,}\n"
        report += f"- Tier 2: {ensemble_data.get('tier2_count', 0):,}\n"
        report += f"- Tier 3: {ensemble_data.get('tier3_count', 0):,}\n"
    
    report += "\n---\n\n## 🎯 Conclusions\n\n"
    report += "This comprehensive analysis identified differentially expressed genes with high confidence.\n\n"
    report += "**Recommended Next Steps:**\n"
    report += "1. Validate top Tier 1 genes (3-5 genes minimum)\n"
    report += "2. Perform pathway enrichment on Tier 1+2 genes\n"
    report += "3. Network analysis for mechanistic insights\n"
    report += "4. Plan follow-up experiments\n"
    
    report += "\n---\n\n*Report generated by RAPTOR v2.2.0*\n"
    
    return report

# ============================================================================
# REPORT GENERATION
# ============================================================================

if "Quality Control" in report_type:
    st.markdown("## 🔬 Quality Control Report")
    
    if st.session_state.get('m2_complete', False):
        st.success("✅ Quality Assessment data available")
        
        if st.button("📋 Generate QC Report", type="primary", use_container_width=True):
            # Get QC data from session state
            qc_data = {
                'overall_score': st.session_state.get('m2_overall_score', 75),
                'component_scores': st.session_state.get('m2_component_scores', {}),
                'outliers_detected': st.session_state.get('m2_n_outliers', 0)
            }
            
            # Generate report
            report_content = generate_qc_report_markdown(qc_data)
            
            # Store in session state
            st.session_state['report_content'] = report_content
            st.session_state['report_type'] = 'qc'
            st.session_state['report_generated'] = True
            
            st.rerun()
    else:
        st.warning("⚠️ Quality Assessment not complete. Please run Module 2 first.")
        if st.button("📥 Go to Module 2"):
            try:
                st.switch_page("pages/01_✅_Quality.py")
            except:
                st.info("Navigate manually to Module 2 (Quality Assessment)")

elif "DE Analysis" in report_type:
    st.markdown("## 🧬 DE Analysis Report")
    
    if st.session_state.get('m7_complete', False):
        st.success("✅ DE Import data available")
        
        # Show what's available
        de_results = st.session_state.get('m7_de_results', {})
        st.info(f"**Available DE Results:** {len(de_results)} file(s)")
        
        if st.button("📋 Generate DE Report", type="primary", use_container_width=True):
            # Generate report
            report_content = generate_de_report_markdown(de_results)
            
            # Store in session state
            st.session_state['report_content'] = report_content
            st.session_state['report_type'] = 'de'
            st.session_state['report_generated'] = True
            
            st.rerun()
    else:
        st.warning("⚠️ DE Import not complete. Please run Module 7 first.")
        if st.button("📥 Go to Module 7"):
            try:
                st.switch_page("pages/04_📥_Import_DE.py")
            except:
                st.info("Navigate manually to Module 7 (Import DE)")

elif "Ensemble" in report_type:
    st.markdown("## 🔬 Ensemble Analysis Report")
    
    if st.session_state.get('m9_complete', False):
        st.success("✅ Ensemble Analysis data available")
        
        # Show what's available
        result = st.session_state.get('m9_result', {})
        st.info(f"**Consensus Genes:** {result.get('n_consensus', 0):,}")
        
        if st.button("📋 Generate Ensemble Report", type="primary", use_container_width=True):
            # Generate report
            report_content = generate_ensemble_report_markdown(result)
            
            # Store in session state
            st.session_state['report_content'] = report_content
            st.session_state['report_type'] = 'ensemble'
            st.session_state['report_generated'] = True
            
            st.rerun()
    else:
        st.warning("⚠️ Ensemble Analysis not complete. Please run Module 9 first.")
        if st.button("📥 Go to Module 9"):
            try:
                st.switch_page("pages/06_🔬_Ensemble.py")
            except:
                st.info("Navigate manually to Module 9 (Ensemble Analysis)")

else:  # Complete Workflow Report
    st.markdown("## 📊 Complete Workflow Report")
    
    # Check what's available
    has_qc = st.session_state.get('m2_complete', False)
    has_de = st.session_state.get('m7_complete', False)
    has_opt = st.session_state.get('m8_complete', False)
    has_ensemble = st.session_state.get('m9_complete', False)
    
    st.markdown("**Available Data:**")
    st.markdown(f"- Quality Control: {'✅' if has_qc else '⬜'}")
    st.markdown(f"- DE Import: {'✅' if has_de else '⬜'}")
    st.markdown(f"- Optimization: {'✅' if has_opt else '⬜'}")
    st.markdown(f"- Ensemble: {'✅' if has_ensemble else '⬜'}")
    
    if has_de or has_ensemble:
        st.success("✅ Sufficient data for complete report")
        
        if st.button("📋 Generate Complete Report", type="primary", use_container_width=True):
            # Gather all available data
            qc_data = {
                'overall_score': st.session_state.get('m2_overall_score'),
                'outliers_detected': st.session_state.get('m2_n_outliers')
            } if has_qc else None
            
            de_data = st.session_state.get('m7_de_results') if has_de else None
            
            opt_data = st.session_state.get('m8_optimized_params') if has_opt else None
            
            ensemble_data = st.session_state.get('m9_result') if has_ensemble else None
            
            # Generate report
            report_content = generate_complete_report_markdown(
                qc_data, de_data, ensemble_data, opt_data
            )
            
            # Store in session state
            st.session_state['report_content'] = report_content
            st.session_state['report_type'] = 'complete'
            st.session_state['report_generated'] = True
            
            st.rerun()
    else:
        st.warning("⚠️ Please complete at least Module 7 (DE Import) or Module 9 (Ensemble) first.")

# ============================================================================
# DISPLAY GENERATED REPORT
# ============================================================================

if st.session_state.get('report_generated', False) and 'report_content' in st.session_state:
    st.markdown("---")
    st.success("✅ Report generated successfully!")
    
    # Preview
    st.markdown("## 📄 Report Preview")
    
    with st.expander("View Report Content", expanded=True):
        st.markdown(st.session_state['report_content'])
    
    # Export options
    st.markdown("---")
    st.markdown("## 💾 Export Report")
    
    col1, col2, col3 = st.columns(3)
    
    with col1:
        # Markdown
        report_type_short = st.session_state.get('report_type', 'report')
        filename_md = f"raptor_{report_type_short}_report.md"
        
        st.download_button(
            label="📥 Download Markdown",
            data=st.session_state['report_content'].encode('utf-8'),
            file_name=filename_md,
            mime="text/markdown",
            use_container_width=True,
            help="Best for GitHub, documentation"
        )
    
    with col2:
        # HTML
        try:
            import markdown
            html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>RAPTOR Analysis Report</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 900px;
            margin: 40px auto;
            padding: 20px;
            line-height: 1.6;
        }}
        h1 {{ color: #2E7D32; border-bottom: 3px solid #2E7D32; }}
        h2 {{ color: #388E3C; border-bottom: 2px solid #388E3C; }}
        h3 {{ color: #4CAF50; }}
        code {{
            background-color: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
        }}
        ul {{ line-height: 1.8; }}
    </style>
</head>
<body>
{markdown.markdown(st.session_state['report_content'])}
</body>
</html>"""
            
            filename_html = f"raptor_{report_type_short}_report.html"
            
            st.download_button(
                label="📥 Download HTML",
                data=html_content.encode('utf-8'),
                file_name=filename_html,
                mime="text/html",
                use_container_width=True,
                help="View in browser, share easily"
            )
        except ImportError:
            st.warning("Install 'markdown' package for HTML export")
    
    with col3:
        # Plain text
        text_content = st.session_state['report_content'].replace('#', '').replace('**', '').replace('*', '')
        filename_txt = f"raptor_{report_type_short}_report.txt"
        
        st.download_button(
            label="📥 Download Text",
            data=text_content.encode('utf-8'),
            file_name=filename_txt,
            mime="text/plain",
            use_container_width=True,
            help="Plain text, maximum compatibility"
        )
    
    # Reset button
    st.markdown("---")
    if st.button("🔄 Generate Different Report"):
        st.session_state['report_generated'] = False
        st.session_state.pop('report_content', None)
        st.rerun()

# Footer
st.markdown("---")
st.caption("💡 **Tip:** Export reports for documentation, publication, and sharing with collaborators")
st.caption("📚 **Formats:** Markdown for GitHub, HTML for browsers, Text for maximum compatibility")
