"""
RAPTOR Dashboard - Reports Generator
=====================================

Generate comprehensive analysis reports from RAPTOR workflow results.

Author: Ayeh Bolouki
Version: 2.2.0
"""

import streamlit as st
import pandas as pd
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional
import sys

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from raptor.dashboard.components.sidebar import render_sidebar, init_session_state

# Page config
st.set_page_config(
    page_title="RAPTOR - Reports",
    page_icon="📋",
    layout="wide"
)

# Initialize
init_session_state()
render_sidebar()

# Main content
st.title("Report Generator")
st.caption("Generate and export analysis reports from your RAPTOR workflow")

# Help section
with st.expander("ℹ️ How to use this module"):
    st.markdown("""
    **Purpose:** Generate professional reports from your RAPTOR analysis results.
    
    ## **Available Report Types**
    
    ### **1. Quality Control Report**
    - Requires: Module 2 (Quality Assessment) complete
    - Contains: Overall quality score, component scores, outlier detection results
    
    ### **2. DE Analysis Report**
    - Requires: Module 7 (Import DE) complete
    - Contains: Per-method statistics, significant genes summary
    
    ### **3. Ensemble Analysis Report**
    - Requires: Module 9 (Ensemble Analysis) complete
    - Contains: Consensus genes, tier breakdown, method comparison
    
    ### **4. Biomarker Discovery Report**
    - Requires: Module 10 (Biomarker Discovery) complete
    - Contains: Panel, classifier performance, signature score, direction
      pattern, clinical metrics (Youden, bootstrap CI, PPV/NPV, DCA),
      ratio biomarkers, biological annotation
    
    ### **5. Complete Workflow Report**
    - Requires: Multiple modules complete
    - Contains: Everything from QC to biomarker discovery
    
    ## **Export Formats**
    
    - **Markdown (.md):** Best for GitHub, documentation
    - **HTML (.html):** View in browser, share easily
    - **Text (.txt):** Plain text, maximum compatibility
    
    ## **Tips**
    
    - Reports pull data from completed modules automatically
    - Export reports for documentation and publication
    - HTML format best for sharing with collaborators
    """)

st.markdown("---")

# Check what's available in session state
st.markdown("## Available Data")

available_modules = []
if st.session_state.get('m2_complete', False):
    available_modules.append("Module 2: Quality Assessment")
else:
    available_modules.append("⬜ Module 2: Quality Assessment")

if st.session_state.get('m7_complete', False):
    available_modules.append("Module 7: DE Import")
else:
    available_modules.append("⬜ Module 7: DE Import")

if st.session_state.get('m8_complete', False):
    available_modules.append("Module 8: Parameter Optimization")
else:
    available_modules.append("⬜ Module 8: Parameter Optimization")

if st.session_state.get('m9_complete', False):
    available_modules.append("Module 9: Ensemble Analysis")
else:
    available_modules.append("⬜ Module 9: Ensemble Analysis")

if st.session_state.get('m10_complete', False):
    available_modules.append("Module 10: Biomarker Discovery")
else:
    available_modules.append("⬜ Module 10: Biomarker Discovery")

for module in available_modules:
    st.markdown(f"- {module}")

st.markdown("---")

# Report type selection
st.markdown("## Select Report Type")

report_type = st.radio(
    "Choose report to generate:",
    [
        "Quality Control Report (Module 2)",
        "DE Analysis Summary (Module 7)",
        "Ensemble Analysis Report (Module 9)",
        "Biomarker Discovery Report (Module 10)",
        "Complete Workflow Report (All Modules)"
    ]
)

st.markdown("---")

# ============================================================================
# REPORT GENERATION FUNCTIONS
# ============================================================================

def generate_qc_report_markdown(qc_data: Dict) -> str:
    """Generate QC report in markdown format."""
    
    report = f"""# RAPTOR Quality Control Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**RAPTOR Version:** 2.2.0

---

## Overall Quality

**Overall Quality Score:** {qc_data.get('overall_score', 'N/A')}/100

"""
    
    if 'component_scores' in qc_data:
        report += "## Component Scores\n\n"
        for component, score in qc_data['component_scores'].items():
            status = "Pass" if score >= 80 else "Warning" if score >= 60 else "Fail"
            report += f"- **{component}:** {score:.1f}/100 {status}\n"
        report += "\n"
    
    if 'outliers_detected' in qc_data:
        report += f"\n## Outlier Detection\n\n"
        report += f"**Outliers Detected:** {qc_data['outliers_detected']} samples\n\n"
    
    report += "\n---\n\n*Report generated by RAPTOR v2.2.0*\n"
    
    return report

def generate_de_report_markdown(de_results: Dict) -> str:
    """Generate DE analysis report in markdown format."""
    
    report = f"""# RAPTOR Differential Expression Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**RAPTOR Version:** 2.2.0

---

## Summary

**Number of DE Result Files:** {len(de_results)}

"""
    
    for file_name, de_result in de_results.items():
        report += f"\n### {file_name}\n\n"
        report += f"- **Pipeline:** {de_result.pipeline}\n"
        report += f"- **Total Genes:** {de_result.n_genes:,}\n"
        report += f"- **Significant Genes:** {de_result.n_significant:,}\n"
        n_up = getattr(de_result, 'n_up', None)
        n_down = getattr(de_result, 'n_down', None)
        if n_up is None and hasattr(de_result, 'results_df') and 'direction' in de_result.results_df.columns:
            n_up = int((de_result.results_df['direction'] == 'up').sum())
            n_down = int((de_result.results_df['direction'] == 'down').sum())
        if n_up is not None:
            report += f"- **Up-regulated:** {n_up:,}\n"
        if n_down is not None:
            report += f"- **Down-regulated:** {n_down:,}\n"
        
        # Calculate percentage
        pct = (de_result.n_significant / de_result.n_genes * 100) if de_result.n_genes > 0 else 0
        report += f"- **% Significant:** {pct:.1f}%\n"
    
    report += "\n---\n\n*Report generated by RAPTOR v2.2.0*\n"
    
    return report

def generate_ensemble_report_markdown(ensemble_result: Dict) -> str:
    """Generate ensemble analysis report in markdown format."""
    
    report = f"""# RAPTOR Ensemble Analysis Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**RAPTOR Version:** 2.2.0

---

## Summary

**Ensemble Method:** {ensemble_result.get('ensemble_method', 'N/A')}  
**Methods Combined:** {ensemble_result.get('n_methods', 0)}  
**Total Consensus Genes:** {ensemble_result.get('n_consensus', 0):,}

---

## 🎯 Confidence Tiers

### Tier 1 (Highest Confidence, p<0.001)
- **Genes:** {ensemble_result.get('tier1_count', 0):,}
- **Use for:** qPCR validation, drug targets

### Tier 2 (High Confidence, p<0.01)
- **Genes:** {ensemble_result.get('tier2_count', 0):,}
- **Use for:** Pathway analysis, GO enrichment

### Tier 3 (Moderate Confidence, p<0.05)
- **Genes:** {ensemble_result.get('tier3_count', 0):,}
- **Use for:** Exploratory analysis

---

## 📋 Input Methods

Methods used in ensemble:
"""
    
    for method in ensemble_result.get('method_names', []):
        report += f"- {method}\n"
    
    report += "\n---\n\n## 💡 Recommendations\n\n"
    report += "- Use **Tier 1 genes** for validation experiments (qPCR, Western blot)\n"
    report += "- Use **Tier 1 + Tier 2** for pathway enrichment analysis\n"
    report += "- Consider all tiers for exploratory network analysis\n"
    
    report += "\n---\n\n*Report generated by RAPTOR v2.2.0*\n"
    
    return report

def generate_biomarker_report_markdown(result) -> str:
    """Generate biomarker discovery report in markdown format.

    ``result`` may be a plain BiomarkerResult or an EnhancedBiomarkerResult.
    The function handles both transparently.
    """
    # Unwrap if this is an EnhancedBiomarkerResult
    base = result.base_result if hasattr(result, 'base_result') else result
    is_enhanced = hasattr(result, 'base_result')

    # Best classifier
    best_clf = base.best_classifier or 'N/A'
    best_auc = 0.0
    best_f1 = 0.0
    if best_clf != 'N/A' and best_clf in base.classification_results:
        cr = base.classification_results[best_clf]
        best_auc = getattr(cr, 'auc', 0.0)
        best_f1 = getattr(cr, 'f1', 0.0)

    report = f"""# RAPTOR Biomarker Discovery Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**RAPTOR Version:** 2.2.2  
**Module:** 10 (Biomarker Discovery)

---

## Summary

**Study design:** {base.study_design}  
**Validation strategy:** {base.validation_strategy}  
**Samples:** {base.n_samples}  
**Initial candidates:** {base.n_initial_candidates:,}  
**Final panel size:** {base.panel_size} genes  
**Best classifier:** {best_clf}  
**Best AUC:** {best_auc:.3f}  
**Best F1:** {best_f1:.3f}

---

## Feature Selection

"""
    for method, sel_res in base.selection_results.items():
        n_sel = getattr(sel_res, 'n_selected', 'N/A')
        report += f"- **{method}:** {n_sel} genes selected\n"

    # ---- Classification performance ----
    report += "\n---\n\n## Classification Performance\n\n"
    report += "| Classifier | AUC | F1 | Accuracy |\n"
    report += "|---|---|---|---|\n"
    for name, cr in base.classification_results.items():
        marker = " *" if name == base.best_classifier else ""
        report += (
            f"| {name}{marker} | "
            f"{getattr(cr, 'auc', 0):.3f} | "
            f"{getattr(cr, 'f1', 0):.3f} | "
            f"{getattr(cr, 'accuracy', 0):.3f} |\n"
        )

    # ---- Panel ----
    report += "\n---\n\n## Recommended Panel\n\n"
    for i, gene in enumerate(base.panel, 1):
        report += f"{i}. `{gene}`\n"

    # ---- Panel optimization ----
    if base.panel_optimization is not None:
        po = base.panel_optimization
        opt_size = getattr(po, 'optimal_size', base.panel_size)
        opt_auc = getattr(po, 'optimal_auc', best_auc)
        report += (
            f"\n**Panel optimization:** optimal size = {opt_size}, "
            f"optimal AUC = {opt_auc:.3f}\n"
        )

    # ---- Enhanced analysis ----
    if is_enhanced:
        report += "\n---\n\n## Enhanced Analysis\n\n"
        intent = result.intent
        report += f"**Intent:** {intent.output_label}  \n"
        report += f"**Study design:** {intent.study_design}  \n"

        # Signature score
        sig = result.signature
        if sig is not None:
            report += f"\n### Signature Score ({sig.mode})\n\n"
            report += f"- Panel genes: {len(sig.panel_genes)}\n"
            report += f"- Risk groups: {' / '.join(sig.risk_labels)}\n"
            if sig.performance:
                for metric, value in sig.performance.items():
                    if isinstance(value, float):
                        report += f"- {metric}: {value:.3f}\n"
                    else:
                        report += f"- {metric}: {value}\n"

        # Direction pattern
        dp = result.direction_pattern
        if dp is not None:
            report += "\n### Direction Pattern\n\n"
            report += f"- UP in reference: {dp.n_up}\n"
            report += f"- DOWN in reference: {dp.n_down}\n"
            report += f"- Total genes: {dp.n_genes}\n"

        # Clinical metrics
        clin = result.clinical_metrics
        if clin:
            report += "\n### Clinical Metrics\n\n"
            if 'youdens' in clin:
                y = clin['youdens']
                report += (
                    f"- **Youden's optimal:** threshold={y['threshold']:.3f}, "
                    f"sensitivity={y['sensitivity']:.3f}, "
                    f"specificity={y['specificity']:.3f}, "
                    f"J={y['youdens_j']:.3f}\n"
                )
            if 'bootstrap_ci' in clin:
                b = clin['bootstrap_ci']
                report += (
                    f"- **AUC 95% CI:** "
                    f"[{b['ci_lower']:.3f}, {b['ci_upper']:.3f}] "
                    f"(n_bootstrap={b['n_bootstrap']})\n"
                )
            if 'ppv_npv' in clin:
                p = clin['ppv_npv']
                report += (
                    f"- **At {p['prevalence']:.1%} prevalence:** "
                    f"PPV={p['ppv']:.3f}, NPV={p['npv']:.3f}\n"
                )
            if 'decision_curve' in clin:
                report += "- **Decision curve analysis:** computed\n"

        # Ratio biomarkers
        rr = result.ratio_result
        if rr is not None and rr.n_found > 0:
            report += "\n### Ratio Biomarkers\n\n"
            report += f"- Pairs found: {rr.n_found}\n"
            report += f"- Pairs tested: {rr.n_pairs_tested:,}\n"
            if rr.best_pair:
                report += (
                    f"- Best pair: `{rr.best_pair.name}` "
                    f"(AUC={rr.best_pair.auc:.3f}, "
                    f"direction={rr.best_pair.direction})\n"
                )

    # ---- Annotation ----
    if base.annotation_result is not None:
        ann = base.annotation_result
        report += "\n---\n\n## Biological Annotation\n\n"
        report += f"- Annotated genes: {ann.n_annotated}\n"
        report += f"- Enriched pathways (FDR<0.05): {ann.n_enriched_pathways}\n"
        if hasattr(ann, 'literature_hits') and ann.literature_hits is not None and not ann.literature_hits.empty:
            report += f"- Genes with literature hits: {len(ann.literature_hits)}\n"
        if hasattr(ann, 'ppi_network') and ann.ppi_network is not None:
            n_edges = len(ann.ppi_network.get('edges', []))
            report += f"- PPI network edges: {n_edges}\n"

    report += "\n---\n\n*Report generated by RAPTOR v2.2.2*\n"
    return report


def generate_complete_report_markdown(
    qc_data: Optional[Dict],
    de_data: Optional[Dict],
    ensemble_data: Optional[Dict],
    opt_data: Optional[Dict],
    biomarker_result=None,
) -> str:
    """Generate complete workflow report."""
    
    report = f"""# RAPTOR Complete Workflow Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**RAPTOR Version:** 2.2.0

---

## Analysis Overview

This report summarizes the complete RAPTOR RNA-seq analysis workflow.

"""
    
    # QC Section
    if qc_data:
        report += "\n## 1. Quality Control\n\n"
        report += f"**Overall Quality Score:** {qc_data.get('overall_score', 'N/A')}/100\n\n"
        if 'outliers_detected' in qc_data:
            report += f"**Outliers Detected:** {qc_data.get('outliers_detected', 0)} samples\n\n"
    
    # DE Section
    if de_data:
        report += "\n## 2. Differential Expression\n\n"
        report += f"**Number of Methods:** {len(de_data)}\n\n"
        
        for file_name, de_result in de_data.items():
            report += f"### {file_name}\n"
            report += f"- Significant genes: {de_result.n_significant:,}\n"
    
    # Optimization Section
    if opt_data:
        report += "\n## 3. Parameter Optimization\n\n"
        params = opt_data.get('parameters', {}) if isinstance(opt_data, dict) else {}
        if params:
            report += f"**FDR Threshold:** {params.get('fdr_threshold', 'N/A')}\n"
            report += f"**Log2FC Threshold:** {params.get('lfc_threshold', 'N/A')}\n"
            report += f"**Optimized DEGs:** {opt_data.get('n_total', 'N/A')}\n"
    
    # Ensemble Section
    if ensemble_data:
        report += "\n## 4. Ensemble Analysis\n\n"
        report += f"**Ensemble Method:** {ensemble_data.get('ensemble_method', 'N/A')}\n"
        report += f"**Consensus Genes:** {ensemble_data.get('n_consensus', 0):,}\n"
        report += f"- Tier 1: {ensemble_data.get('tier1_count', 0):,}\n"
        report += f"- Tier 2: {ensemble_data.get('tier2_count', 0):,}\n"
        report += f"- Tier 3: {ensemble_data.get('tier3_count', 0):,}\n"

    # Biomarker Discovery Section
    if biomarker_result is not None:
        base_br = (
            biomarker_result.base_result
            if hasattr(biomarker_result, 'base_result') else biomarker_result
        )
        best_clf = base_br.best_classifier or 'N/A'
        best_auc = 0.0
        if best_clf != 'N/A' and best_clf in base_br.classification_results:
            best_auc = getattr(
                base_br.classification_results[best_clf], 'auc', 0.0
            )

        report += "\n## 5. Biomarker Discovery\n\n"
        report += f"**Panel size:** {base_br.panel_size} genes\n"
        report += f"**Best classifier:** {best_clf}\n"
        report += f"**Best AUC:** {best_auc:.3f}\n"
        report += f"**Panel:** `{', '.join(base_br.panel[:10])}`"
        if len(base_br.panel) > 10:
            report += f" (+ {len(base_br.panel) - 10} more)"
        report += "\n"

        if hasattr(biomarker_result, 'base_result'):
            # Enhanced result — add intent + clinical metrics summary
            intent = biomarker_result.intent
            report += f"**Intent:** {intent.output_label}\n"
            clin = biomarker_result.clinical_metrics
            if clin and 'bootstrap_ci' in clin:
                b = clin['bootstrap_ci']
                report += (
                    f"**AUC 95% CI:** "
                    f"[{b['ci_lower']:.3f}, {b['ci_upper']:.3f}]\n"
                )

    report += "\n---\n\n## Conclusions\n\n"
    report += "This comprehensive analysis identified differentially expressed genes with high confidence.\n\n"
    report += "**Recommended Next Steps:**\n"
    report += "1. Validate top Tier 1 genes (3-5 genes minimum)\n"
    report += "2. Perform pathway enrichment on Tier 1+2 genes\n"
    report += "3. Network analysis for mechanistic insights\n"
    report += "4. Plan follow-up experiments\n"
    
    report += "\n---\n\n*Report generated by RAPTOR v2.2.0*\n"
    
    return report

# ============================================================================
# REPORT GENERATION
# ============================================================================

if "Quality Control" in report_type:
    st.markdown("## Quality Control Report")
    
    if st.session_state.get('m2_complete', False):
        st.success("Quality Assessment data available")
        
        if st.button("Generate QC Report", type="primary", use_container_width=True):
            # Get QC data from session state
            # Read from actual session state keys set by Quality page
            qc_report = st.session_state.get('m2_qc_report', {})
            outlier_result = st.session_state.get('m2_outlier_result', None)
            qc_data = {
                'overall_score': qc_report.get('overall', {}).get('score', 'N/A'),
                'overall_status': qc_report.get('overall', {}).get('status', 'unknown'),
                'component_scores': {
                    k: v.get('score', 0) 
                    for k, v in qc_report.get('components', {}).items()
                    if isinstance(v, dict) and 'score' in v
                },
                'outliers_detected': outlier_result.n_outliers if outlier_result else 0,
                'outlier_samples': list(outlier_result.outlier_samples) if outlier_result and outlier_result.n_outliers > 0 else []
            }
            
            # Generate report
            report_content = generate_qc_report_markdown(qc_data)
            
            # Store in session state
            st.session_state['report_content'] = report_content
            st.session_state['report_type'] = 'qc'
            st.session_state['report_generated'] = True
            
            st.rerun()
    else:
        st.warning("Quality Assessment not complete. Please run Module 2 first.")
        if st.button("Go to Module 2"):
            try:
                st.switch_page("pages/01_✅_Quality.py")
            except:
                st.info("Navigate manually to Module 2 (Quality Assessment)")

elif "DE Analysis" in report_type:
    st.markdown("## DE Analysis Report")
    
    if st.session_state.get('m7_complete', False):
        st.success("DE Import data available")
        
        # Show what's available
        de_results = st.session_state.get('m7_de_results', {})
        st.info(f"**Available DE Results:** {len(de_results)} file(s)")
        
        if st.button("Generate DE Report", type="primary", use_container_width=True):
            # Generate report
            report_content = generate_de_report_markdown(de_results)
            
            # Store in session state
            st.session_state['report_content'] = report_content
            st.session_state['report_type'] = 'de'
            st.session_state['report_generated'] = True
            
            st.rerun()
    else:
        st.warning("DE Import not complete. Please run Module 7 first.")
        if st.button("Go to Module 7"):
            try:
                st.switch_page("pages/04_📥_Import_DE.py")
            except:
                st.info("Navigate manually to Module 7 (Import DE)")

elif "Ensemble" in report_type:
    st.markdown("## Ensemble Analysis Report")
    
    if st.session_state.get('m9_complete', False):
        st.success("Ensemble Analysis data available")
        
        # Show what's available
        result = st.session_state.get('m9_result', {})
        st.info(f"**Consensus Genes:** {result.get('n_consensus', 0):,}")
        
        if st.button("Generate Ensemble Report", type="primary", use_container_width=True):
            # Generate report
            report_content = generate_ensemble_report_markdown(result)
            
            # Store in session state
            st.session_state['report_content'] = report_content
            st.session_state['report_type'] = 'ensemble'
            st.session_state['report_generated'] = True
            
            st.rerun()
    else:
        st.warning("Ensemble Analysis not complete. Please run Module 9 first.")
        if st.button("Go to Module 9"):
            try:
                st.switch_page("pages/06_🔬_Ensemble.py")
            except:
                st.info("Navigate manually to Module 9 (Ensemble Analysis)")

elif "Biomarker Discovery" in report_type:
    st.markdown("## Biomarker Discovery Report")

    if st.session_state.get('m10_complete', False):
        st.success("Biomarker Discovery data available")

        result = st.session_state.get('m10_result')
        if result is not None:
            base = result.base_result if hasattr(result, 'base_result') else result
            st.info(
                f"**Panel size:** {base.panel_size} genes | "
                f"**Best classifier:** {base.best_classifier or 'N/A'} | "
                f"**Samples:** {base.n_samples}"
            )

            if st.button("Generate Biomarker Report", type="primary", use_container_width=True):
                report_content = generate_biomarker_report_markdown(result)

                st.session_state['report_content'] = report_content
                st.session_state['report_type'] = 'biomarker'
                st.session_state['report_generated'] = True

                st.rerun()
    else:
        st.warning("Biomarker Discovery not complete. Please run Module 10 first.")
        if st.button("Go to Module 10"):
            try:
                st.switch_page("pages/08___Biomarker_Discovery.py")
            except Exception:
                st.info("Navigate manually to Module 10 (Biomarker Discovery)")

else:  # Complete Workflow Report
    st.markdown("## Complete Workflow Report")
    
    # Check what's available
    has_qc = st.session_state.get('m2_complete', False)
    has_de = st.session_state.get('m7_complete', False)
    has_opt = st.session_state.get('m8_complete', False)
    has_ensemble = st.session_state.get('m9_complete', False)
    has_biomarker = st.session_state.get('m10_complete', False)
    
    st.markdown("**Available Data:**")
    st.markdown(f"- Quality Control: {'Pass' if has_qc else '⬜'}")
    st.markdown(f"- DE Import: {'Pass' if has_de else '⬜'}")
    st.markdown(f"- Optimization: {'Pass' if has_opt else '⬜'}")
    st.markdown(f"- Ensemble: {'Pass' if has_ensemble else '⬜'}")
    st.markdown(f"- Biomarker Discovery: {'Pass' if has_biomarker else '⬜'}")
    
    if has_de or has_ensemble or has_biomarker:
        st.success("Sufficient data for complete report")
        
        if st.button("Generate Complete Report", type="primary", use_container_width=True):
            # Gather all available data
            qc_report = st.session_state.get('m2_qc_report', {})
            outlier_result = st.session_state.get('m2_outlier_result', None)
            qc_data = {
                'overall_score': qc_report.get('overall', {}).get('score', 'N/A'),
                'outliers_detected': outlier_result.n_outliers if outlier_result else 0
            } if has_qc else None
            
            de_data = st.session_state.get('m7_de_results') if has_de else None
            
            opt_data = st.session_state.get('m8_optimized_params')
            if opt_data is None and has_opt:
                opt_result = st.session_state.get('m8_opt_result')
                if opt_result:
                    opt_data = {
                        'parameters': opt_result.best_parameters,
                        'n_total': opt_result.n_deg_genes,
                        'score': opt_result.best_score
                    }
            
            ensemble_data = st.session_state.get('m9_result') if has_ensemble else None
            biomarker_result = st.session_state.get('m10_result') if has_biomarker else None
            
            # Generate report
            report_content = generate_complete_report_markdown(
                qc_data, de_data, ensemble_data, opt_data,
                biomarker_result=biomarker_result,
            )
            
            # Store in session state
            st.session_state['report_content'] = report_content
            st.session_state['report_type'] = 'complete'
            st.session_state['report_generated'] = True
            
            st.rerun()
    else:
        st.warning("Please complete at least Module 7 (DE Import), Module 9 (Ensemble), or Module 10 (Biomarker Discovery) first.")

# ============================================================================
# DISPLAY GENERATED REPORT
# ============================================================================

if st.session_state.get('report_generated', False) and 'report_content' in st.session_state:
    st.markdown("---")
    st.success("Report generated successfully!")
    
    # Preview
    st.markdown("## 📄 Report Preview")
    
    with st.expander("View Report Content", expanded=True):
        st.markdown(st.session_state['report_content'])
    
    # Export options
    st.markdown("---")
    st.markdown("## 💾 Export Report")
    
    col1, col2, col3 = st.columns(3)
    
    with col1:
        # Markdown
        report_type_short = st.session_state.get('report_type', 'report')
        filename_md = f"raptor_{report_type_short}_report.md"
        
        st.download_button(
            label="Download Markdown",
            data=st.session_state['report_content'].encode('utf-8'),
            file_name=filename_md,
            mime="text/markdown",
            use_container_width=True,
            help="Best for GitHub, documentation"
        )
    
    with col2:
        # HTML
        try:
            import markdown
            html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>RAPTOR Analysis Report</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 900px;
            margin: 40px auto;
            padding: 20px;
            line-height: 1.6;
        }}
        h1 {{ color: #2E7D32; border-bottom: 3px solid #2E7D32; }}
        h2 {{ color: #388E3C; border-bottom: 2px solid #388E3C; }}
        h3 {{ color: #4CAF50; }}
        code {{
            background-color: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
        }}
        ul {{ line-height: 1.8; }}
    </style>
</head>
<body>
{markdown.markdown(st.session_state['report_content'])}
</body>
</html>"""
            
            filename_html = f"raptor_{report_type_short}_report.html"
            
            st.download_button(
                label="Download HTML",
                data=html_content.encode('utf-8'),
                file_name=filename_html,
                mime="text/html",
                use_container_width=True,
                help="View in browser, share easily"
            )
        except ImportError:
            st.warning("Install 'markdown' package for HTML export")
    
    with col3:
        # Plain text
        text_content = st.session_state['report_content'].replace('#', '').replace('**', '').replace('*', '')
        filename_txt = f"raptor_{report_type_short}_report.txt"
        
        st.download_button(
            label="Download Text",
            data=text_content.encode('utf-8'),
            file_name=filename_txt,
            mime="text/plain",
            use_container_width=True,
            help="Plain text, maximum compatibility"
        )
    
    # Reset button
    st.markdown("---")
    if st.button("Generate Different Report"):
        st.session_state['report_generated'] = False
        st.session_state.pop('report_content', None)
        st.rerun()

# Footer
st.markdown("---")
st.caption("**Tip:** Export reports for documentation, publication, and sharing with collaborators")
st.caption("**Formats:** Markdown for GitHub, HTML for browsers, Text for maximum compatibility")